services:

  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - backend/.env.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d app" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: